language: php

php:
  - '5.6'
  - '7.0'

sudo: false 

env:
  - GITHUB_OAUTH_TOKEN=3528dd74a54dddde076a3b6607ac11de8360e85b

before_install: 
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - touch storage/database.sqlite

install:
  - travis_retry composer install --no-interaction
  - composer require satooshi/php-coveralls:~0.6@stable

before_script: 
  - git reset --hard HEAD
  - cp .env.example .env
  - php pulse key:generate
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpspec
  - php pulse

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

notifications:
  email: false
