language: php

php:
  - '5.6'
  - '7.0'
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

sudo: false 

env:
  - GITHUB_OAUTH_TOKEN=3528dd74a54dddde076a3b6607ac11de8360e85b

before_install: 
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - touch storage/database.sqlite

install: 
  - travis_retry composer install --no-interaction

before_script: 
  - git reset --hard HEAD
  - cp .env.example .env

script:
  - vendor/bin/phpunit
  - vendor/bin/phpspec
  - php artisan

notifications:
  email: false
