language: php
php:
- '5.6'
- '7.0'
- '7.1'
env:
  matrix:
  global:
    secure: r3ojSjWRN0QYwlyR2URoIRKKInaiYKAH5JTG3/ILq3vCe+QzysJwi5WEOkkZ347JAr2ZzxMd7IJNWnd0rtOfPfsRuaSR/dqlLuR1JlJBtWcYmpJO2oM0NkPCMg3kMfx/q9VHcN+o/tsyrWzc8rQThbTi4Q5WB6nG5HkrvXvDvRU15T9gnTY8TyuP39+lv/GMzIzIhKwCGbvDDwkKwDFjeh/nXcheUpDD5o+FmyroeBSbF5YibyWG1WW70g49B3TKS+FGPckxN52ftx5H8Mth4UC2fo0VQiG3SLMdTjFE1dVZt49PbIm3U3OEltDv9FabFvachCMgCm0nT3Z3lR+8btsOIxl0/BwW4bKLo+Y31/yO1IdUqWFNxzbAPUNpQIiJ0CHq/frb5FihjE05La9bnlv55W3a1sPEOuf6LaWr8u+qDvash6sSPch3fiMa1wJYqJ6lu2jzZdWCnQ+zafKigOuAYyIzqSsDKukw+uiTXdAEr/jhh6Qd4K/wHZz7r1IZBdadH9fO6rqSiTDi0WFx1foZHCFdobmK3NkB1HGWKt5Xvao4sU/QcGcCOtHe1sqmPw73CftlYuxYnyYls4W3i/M6QpTY+TXzOfJDs948e00ClYAkNeFVm6GUVXowhkG8L9+qAfuhKK+R2ZxM0BehPpU7dfDFqGlKKqh443YiZvk=  
before_install:
- git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
- touch storage/database.sqlite
install:
- travis_retry composer install --no-interaction
before_script:
- git reset --hard HEAD
- cp .env.example .env
- php artisan key:generate
script:
- vendor/bin/phpunit --coverage-clover=coverage.xml
after_script:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
