language: php
php:
- '5.6'
- '7.0'
env:
  matrix:
  - secure: r3ojSjWRN0QYwlyR2URoIRKKInaiYKAH5JTG3/ILq3vCe+QzysJwi5WEOkkZ347JAr2ZzxMd7IJNWnd0rtOfPfsRuaSR/dqlLuR1JlJBtWcYmpJO2oM0NkPCMg3kMfx/q9VHcN+o/tsyrWzc8rQThbTi4Q5WB6nG5HkrvXvDvRU15T9gnTY8TyuP39+lv/GMzIzIhKwCGbvDDwkKwDFjeh/nXcheUpDD5o+FmyroeBSbF5YibyWG1WW70g49B3TKS+FGPckxN52ftx5H8Mth4UC2fo0VQiG3SLMdTjFE1dVZt49PbIm3U3OEltDv9FabFvachCMgCm0nT3Z3lR+8btsOIxl0/BwW4bKLo+Y31/yO1IdUqWFNxzbAPUNpQIiJ0CHq/frb5FihjE05La9bnlv55W3a1sPEOuf6LaWr8u+qDvash6sSPch3fiMa1wJYqJ6lu2jzZdWCnQ+zafKigOuAYyIzqSsDKukw+uiTXdAEr/jhh6Qd4K/wHZz7r1IZBdadH9fO6rqSiTDi0WFx1foZHCFdobmK3NkB1HGWKt5Xvao4sU/QcGcCOtHe1sqmPw73CftlYuxYnyYls4W3i/M6QpTY+TXzOfJDs948e00ClYAkNeFVm6GUVXowhkG8L9+qAfuhKK+R2ZxM0BehPpU7dfDFqGlKKqh443YiZvk=
  global:
    secure: tJwc1hOqNMuG+0A19SXgRQ0cHcW1f5SsGQncsljanyt3ualr2bQCKW4IgM1KCI5M6bI7UO4TosEolLCc/IunJhSrvVoUdREBeALItZGJp8BM+8trD/MYUqkUQQWQwL6JM9N7gD0bB+vfYYSpkglpUJpvYCCow+rfU6oK+y1tfQDZAoZiyqP0fdV4/od0zq5IzC9EHugVietCNMWLh0/f6AqO8b+OIOTALs3Z7Zs1CkbBmkXPPVZFo3v6Qa1fDv6X6ktpg3j7l01yY65ESXDpQkX8sxnp3YFh9eqohdZ8xO4ZKRIi9YVFPtbxeAJhvwpG3PCHV6G+yEmlMbkGigppb3E681BL3F7mNnX8NUUXmper1oNDIlA0gWYymnmDAkWrXd4ORQ+bCNJaetudYpMWwOdtF8OL8ouotxC0VvuVh7CIyk+WZF4B216V/H9efn7gKxFwfcKjXxv+0WTaWHpZf4PAhpz8Z2XZUTadyTRQtFAH3+0opoX7gGZ6heqRDFJXv1+uepkG5oTYaanTBQkZ8caSMi+i7qF5bpVrVLzf97lRStcjAsVRzDZqiBJFBRrJV/T1kYSlP8wA+C6pv6Cg2JvFbqlXaTl4QxUkLB75BW8YQN5VCwEHYZ6vo1oZax4CgjDdAJPTjcanlrI+ztk5rnxB6Pgkvx632ejvkFlD8i4=
before_install:
- git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
- touch storage/database.sqlite
install:
- travis_retry composer install --no-interaction
before_script:
- git reset --hard HEAD
- cp .env.example .env
- php pulse key:generate
- mkdir -p build/logs
script:
- vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
after_script:
- php vendor/bin/codacycoverage clover
notifications:
  email: false
